name: Aufgabe1

on:
  push:
    branches: ["main"]
  pull_request:
    types:
      - opened
    branches: ["main"]
jobs:
  unit_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout_code
        uses: actions/checkout@v2

      - name: install_go
        run: sudo apt install golang-go
      - name: run_tests
        run: |
          cd backend
          go run ./...
