name: CVE-Scan

on:
  schedule:
  - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
      
  CVE-Scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout_code
        uses: actions/checkout@v4
        
      - name: Manual Trivy Setup
        uses: aquasecurity/setup-trivy@v0.2.2
        with:
          cache: true
          version: v0.57.1
   

      - name: Sec-test
        run: trivy fs --format template --output ./trivy-scan.html --template "@./trivy-html-report-template.tpl" .
      
        