name: CVE-Scan

on:
  schedule:
  - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
      
  CVE-Scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout_code
        uses: actions/checkout@v3
      
      - name: Sec-test
        run: trivy fs --format template --output ./trivy-scan.html --template "@./trivy-html-report-template.tpl" .